# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  request_changes_workflow: false
  allow_author_approval: false
  review_progress: false
  commit_status: true
  fail_commit_status: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    auto_pause_after_reviewed_commits: 0
