import { expect, test } from "@playwright/test";
import { importSyntheticArchive } from "./fixtures/archive";
import { BlobWriter, TextReader, ZipWriter } from "@zip.js/zip.js";

test("profile-specific evidence edits can be reviewed, undone and discarded without changing the shared collection", async ({ page }) => {
	const remoteWrites: string[] = [];
	page.on("request", (request) => { if (request.method() !== "GET" && request.method() !== "HEAD") remoteWrites.push(request.url()); });
	await importSyntheticArchive(page, "/year-room");
	await expect(page.locator(".selection-summary").first()).toContainText("2 measured messages from 2 eligible");
	await page.getByLabel("Literal phrase to review").fill("remember");
	await page.getByRole("button", { name: "Preview literal matches", exact: true }).click();
	await expect(page.locator(".topic-preview")).toContainText("1 exact matching messages");
	await expect(page.locator(".selection-summary").first()).toContainText("2 measured");
	await page.getByRole("button", { name: "Remove reviewed matches from profile", exact: true }).click();
	await expect(page.locator(".selection-summary").first()).toContainText("1 measured messages from 2 eligible");
	await expect(page.getByText(/Shared collection decisions are unchanged/)).toBeVisible();
	await page.getByRole("button", { name: "Undo profile edit", exact: true }).click();
	await expect(page.locator(".selection-summary").first()).toContainText("2 measured");
	await page.getByRole("button", { name: "Remove from this profile", exact: true }).first().click();
	await expect(page.locator(".selection-summary").first()).toContainText("1 measured messages from 2 eligible");
	await page.getByRole("button", { name: "Restore profile evidence", exact: true }).click();
	await expect(page.locator(".selection-summary").first()).toContainText("2 measured");
	await page.getByRole("button", { name: "Discard this local profile", exact: true }).click();
	await expect(page.getByRole("heading", { name: "Local profile discarded", exact: true })).toBeVisible();
	await expect(page.locator(".example-grid")).toHaveCount(0);
	await page.getByRole("button", { name: "Generate local profile", exact: true }).click();
	await expect(page.locator(".selection-summary").first()).toContainText("2 measured messages from 2 eligible");
	expect(remoteWrites).toEqual([]);
});

test("style preferences preserve measurements and the inspected local packet invalidates after an evidence edit", async ({ page }) => {
	await importSyntheticArchive(page, "/year-room");
	await expect(page.locator(".measurement-grid")).toBeVisible();
	const measured = await page.locator(".measurement-grid").innerText();
	await page.getByLabel("Punctuation preference").selectOption("restrained");
	await expect(page.locator(".measurement-grid")).toBeVisible();
	await expect(page.locator(".measurement-grid")).toHaveText(measured.replaceAll(/\s+/g, " "), { useInnerText: true });
	await page.getByRole("button", { name: "Inspect local evidence packet", exact: true }).click();
	await expect(page.locator(".packet-section pre")).toContainText('"punctuation": "restrained"');
	await expect(page.getByRole("button", { name: "Approve and send unavailable", exact: true })).toBeDisabled();
	await page.getByRole("button", { name: "Remove from this profile", exact: true }).first().click();
	await expect(page.locator(".selection-summary").first()).toContainText("1 measured");
	await expect(page.locator(".packet-section pre")).toHaveCount(0);
	await expect(page.getByLabel("Punctuation preference")).toHaveValue("restrained");
});

test("source round trips retain private profile edits, preferences, undo and discard state", async ({ page }) => {
	await importSyntheticArchive(page, "/year-room");
	await expect(page.locator(".selection-summary").first()).toContainText("2 measured messages from 2 eligible");
	await page.getByRole("button", { name: "Remove from this profile", exact: true }).first().click();
	await expect(page.locator(".selection-summary").first()).toContainText("1 measured messages from 2 eligible");
	await page.getByLabel("Punctuation preference").selectOption("restrained");
	await page.locator(".example-grid").getByRole("link", { name: "Open source →", exact: true }).first().click();
	await expect(page.locator(".thread-heading h2")).toBeVisible();
	await expect(page.locator(".year-room-page")).toHaveCount(0);
	await page.goBack();
	await expect(page.locator(".selection-summary").first()).toContainText("1 measured messages from 2 eligible");
	await expect(page.getByLabel("Punctuation preference")).toHaveValue("restrained");
	await page.getByRole("button", { name: "Undo profile edit", exact: true }).click();
	await expect(page.locator(".selection-summary").first()).toContainText("2 measured messages from 2 eligible");
	await page.getByRole("button", { name: "Discard this local profile", exact: true }).click();
	await expect(page.getByRole("heading", { name: "Local profile discarded", exact: true })).toBeVisible();
	await page.getByRole("navigation", { name: "Main navigation", exact: true }).getByRole("link", { name: "Conversations", exact: true }).click();
	await expect(page.locator(".thread-heading h2")).toBeVisible();
	await page.goBack();
	await expect(page.getByRole("heading", { name: "Local profile discarded", exact: true })).toBeVisible();
	await expect(page.locator(".example-grid")).toHaveCount(0);
	await page.getByRole("button", { name: "Generate local profile", exact: true }).click();
	await expect(page.locator(".selection-summary").first()).toContainText("2 measured messages from 2 eligible");
	await expect(page.getByLabel("Punctuation preference")).toHaveValue("measured");
});

test("every literal matching source is inspectable before applying a frozen profile removal", async ({ page }) => {
	const writer = new ZipWriter(new BlobWriter("application/zip"), { useWebWorkers: false });
	await writer.add("json/account.json", new TextReader('{"Basic Information":{"Username":"synthetic-owner"}}'));
	const records = Array.from({ length: 11 }, (_, index) => ({ From: "synthetic-owner", IsSender: true,
		Created: `2019-01-${String(index + 1).padStart(2, "0")} 12:00:00 UTC`, "Media Type": "TEXT", Content: `keep-this-phrase item ${index + 1}${index === 10 ? " final source" : ""}` }));
	await writer.add("json/chat_history.json", new TextReader(JSON.stringify({ "synthetic-friend": records })));
	await writer.add("json/memories_history.json", new TextReader(JSON.stringify({ "Saved Media": [{ Date: "2012-01-01 12:00:00 UTC", "Media Type": "Image", "Download Link": "https://example.invalid/?mid=missing-old-memory" }] })));
	await page.goto("/import");
	await page.locator('input[type="file"]').setInputFiles({ name: "synthetic-profile-paging.zip", mimeType: "application/zip", buffer: Buffer.from(await (await writer.close()).arrayBuffer()) });
	await page.getByRole("button", { name: "Open the box", exact: true }).click();
	await expect(page.getByRole("heading", { name: "Your archive is ready", exact: true })).toBeVisible();
	await page.getByRole("link", { name: "Past self", exact: true }).click();
	await expect(page.locator(".selection-summary").first()).toContainText("11 measured messages from 11 eligible");
	await page.getByLabel("Literal phrase to review").fill("keep-this-phrase");
	await page.getByRole("button", { name: "Preview literal matches", exact: true }).click();
	await expect(page.locator(".topic-preview li")).toHaveCount(8);
	await page.getByRole("button", { name: "Next matching sources", exact: true }).click();
	await expect(page.locator(".topic-preview li")).toHaveCount(3);
	const last = page.locator(".topic-preview li").filter({ hasText: "keep-this-phrase item 11 final source" });
	await expect(last).toBeVisible();
	const source = last.getByRole("link", { name: "Open matching source →", exact: true });
	const target = await source.getAttribute("href");
	await source.click();
	await expect(page.locator(".thread-heading h2")).toBeVisible();
	await expect(page).toHaveURL(new RegExp(target!.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "$"));
	await page.locator(".message").filter({ hasText: "keep-this-phrase item 11 final source" }).getByRole("button", { name: "Source", exact: true }).click();
	await expect(page.locator(".source-panel")).toContainText("json/chat_history.json/synthetic-friend/10");
	await page.goBack();
	await expect(page.locator(".selection-summary").first()).toContainText("11 measured messages");
	await page.getByLabel("Literal phrase to review").fill("keep-this-phrase");
	await page.getByRole("button", { name: "Preview literal matches", exact: true }).click();
	await page.getByLabel("Punctuation preference").selectOption("restrained");
	await expect(page.locator(".topic-preview")).toHaveCount(0);
	await page.getByRole("button", { name: "Preview literal matches", exact: true }).click();
	await page.getByRole("button", { name: "Remove reviewed matches from profile", exact: true }).click();
	await expect(page.locator(".selection-summary").first()).toContainText("0 measured messages from 11 eligible");
});
